CREATE TABLE CURRENCY_NAME_MAP(
	ENGLISH_NAME VARCHAR2(255) PRIMARY KEY,
	CHINESE_NAME VARCHAR2(255) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	CREATE_BY VARCHAR2(255),
	UPDATE_DATE DATE,
	UPDATE_BY VARCHAR2(255),
	REMARK VARCHAR2(255)
);