spring:
  application:
    name: KpiServer
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:currency
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

server:
  port: 9100
  servlet:
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true